# Generated by Django 5.2 on 2025-04-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rival', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=10)),
            ],
        ),
    ]
